env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - prettier
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
plugins:
  - prettier
  - "@typescript-eslint"
